### ISSUE TITLE
Formatting and functional bits of the generated code are tightly coupled in generator

### ISSUE THREAD

**Issue by rtzoeller** [haven1433/autoimplement#4]
The generator doesn't clearly differentiate between the formatting and functional bits of the generated code, which makes it hard to extend the generator to produce code in a different style and hurts the readability of the generator.

A few examples:
- [`StringWriter.Indent()`](https://github.com/haven1433/autoimplement/blob/b732aae36616990e87d266ebf132ed8bfb054523/AutoImplement/StringWriter.cs#L20) describes a side effect of the `IDisposable` it creates, rather than the functionality. The brackets generated by `IndentationScope` are the semantically important part, not the whitespace. This appears to be addressed by #3.
- The [number of spaces used for one level of indentation](https://github.com/haven1433/autoimplement/blob/b732aae36616990e87d266ebf132ed8bfb054523/AutoImplement/StringWriter.cs#L31) is hard-coded relatively deep in the generator, instead of being configurable.
- The name formatting scheme used to implement functionality is hard coded at the generation site, e.g. with delegate generation. From the changes on #3 notice the repeated use of "Delegate_"/"Delegates_": https://github.com/haven1433/autoimplement/blob/fc4e0db909b493828ced5c85c76ad845fa0f3398/AutoImplement/StubBuilder.cs#L224-L230

**Comment by haven1433** [comment]
It's the StubBuilder's job to make sure that the code it generates can compile, is fairly regular, and is easy to use. So having name formatting schemes hard coded at the generation site seems correct. It most definitely should not be hard coded anywhere else. However, I was able to pull the complex names out to just above and give them more reasonable names, making the generator code slightly cleaner (and hopefully easier) to read. Also, based on something else that had been bugging me (and your comment here giving me an idea of how to fix it), the IPatternBuilder implementations are now also in charge of deciding the names of the files that will hold their implementations.

Good suggestion on making the indentation configurable. That'll be in the pull request update.
